"""
Multi-E3 ligase library tests (beyond CRBN/VHL).
=================================================
The library (protacxtend/data/curated_e3_ligands.csv, generated by
scripts/build_e3_library.py from SynGlue_Py/data/e3_ligand.csv) covers 19
E3 groups with cited ligands. These tests verify selection, provenance and
natural-language E3 detection.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from protacxtend.agents.real_nodes import _detect_e3_from_prompt, _e3  # noqa: E402
from protacxtend.tools.protac_toolbox import (  # noqa: E402
    E3_ALIASES,
    ProtacDesignToolbox,
)

EXPECTED_E3_GROUPS = {
    "CRBN": "pomalidomide", "VHL": "vh032", "cIAP1": "bestatin",
    "MDM2": "Nutlin", "KEAP1": "KI-696", "DCAF15": "ns(=o)(=o)c1ccc",  # indisulam signature
    "RNF114": "Nimbolide", "AhR": "naphthoflavone", "XIAP": "XIAP",
}


class TestMultiE3Selection:
    @pytest.mark.parametrize("e3,expected_fragment", list(EXPECTED_E3_GROUPS.items()))
    def test_select_returns_cited_ligand(self, e3, expected_fragment):
        toolbox = ProtacDesignToolbox()
        ligs = toolbox.select_e3_ligands(e3_ligase=e3, max_ligands_per_e3=3)
        assert ligs, f"no ligands for {e3}"
        haystack = " ".join((l.name + " " + l.smiles) for l in ligs).lower()
        assert expected_fragment.lower() in haystack, f"{expected_fragment} not in {ligs[0].name}"

    def test_provenance_has_doi(self):
        toolbox = ProtacDesignToolbox()
        ligs = toolbox.select_e3_ligands(e3_ligase="MDM2", max_ligands_per_e3=1)
        assert ligs
        assert ligs[0].provenance.get("article_doi"), "DOI provenance missing"
        assert ligs[0].provenance.get("uniprot")

    def test_synonym_case_insensitive(self):
        toolbox = ProtacDesignToolbox()
        a = toolbox.select_e3_ligands(e3_ligase="keap1", max_ligands_per_e3=1)
        b = toolbox.select_e3_ligands(e3_ligase="KEAP1", max_ligands_per_e3=1)
        assert a and b and a[0].smiles == b[0].smiles

    def test_all_library_smiles_valid(self):
        toolbox = ProtacDesignToolbox()
        from rdkit import Chem
        bad = []
        for row in toolbox.load_curated_e3_ligands():
            smi = row.get("smiles", "")
            if smi and Chem.MolFromSmiles(smi.replace("[*:1]", "[*]")) is None:
                bad.append(row.get("name"))
        assert not bad, f"invalid SMILES: {bad}"

    def test_unknown_e3_returns_empty(self):
        toolbox = ProtacDesignToolbox()
        assert toolbox.select_e3_ligands(e3_ligase="NOT_AN_E3") == []


class TestE3Detection:
    @pytest.mark.parametrize("prompt,expected", [
        ("Design MDM2-recruiting PROTACs against p53", "MDM2"),
        ("Design PROTACs recruiting KEAP1 for Nrf2", "KEAP1"),
        ("Use the AhR E3 ligase for this design", "AhR"),
        ("Recruit the cIAP1 ligase for degradation", "cIAP1"),
        ("Design CRBN PROTACs against BRD4", "CRBN"),
    ])
    def test_detection(self, prompt, expected):
        assert _detect_e3_from_prompt(prompt) == expected

    def test_e3_node_populates_state(self):
        out = _e3({"user_request": "Design MDM2-recruiting PROTAC candidates against p53",
                   "parsed_objective": {"target_name": "p53"}})
        assert out.get("selected_e3_ligands")
        assert out["parsed_objective"]["e3"] == "MDM2"
        assert out["evidence"]["e3"]["requested"] == "MDM2"

    def test_e3_node_fallback_to_crbn(self):
        out = _e3({"user_request": "Design PROTACs against something",
                   "parsed_objective": {}})
        assert out["parsed_objective"]["e3"] == "CRBN"


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
